/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coordinates } from './coordinates';


export interface CreatePlayerDTO { 
    username?: string;
    gameId?: string;
    characterClass?: CreatePlayerDTO.CharacterClassEnum;
    characterRace?: CreatePlayerDTO.CharacterRaceEnum;
    healthPoints?: number;
    strength?: number;
    intelligence?: number;
    constitution?: number;
    wisdom?: number;
    dexterity?: number;
    coordinates?: Coordinates;
    characterType?: CreatePlayerDTO.CharacterTypeEnum;
}
export namespace CreatePlayerDTO {
    export type CharacterClassEnum = 'MAGE' | 'FIGHTER' | 'THIEF';
    export const CharacterClassEnum = {
        Mage: 'MAGE' as CharacterClassEnum,
        Fighter: 'FIGHTER' as CharacterClassEnum,
        Thief: 'THIEF' as CharacterClassEnum
    };
    export type CharacterRaceEnum = 'DWARF' | 'ELF' | 'HOBBIT';
    export const CharacterRaceEnum = {
        Dwarf: 'DWARF' as CharacterRaceEnum,
        Elf: 'ELF' as CharacterRaceEnum,
        Hobbit: 'HOBBIT' as CharacterRaceEnum
    };
    export type CharacterTypeEnum = 'Monster' | 'Player';
    export const CharacterTypeEnum = {
        Monster: 'Monster' as CharacterTypeEnum,
        Player: 'Player' as CharacterTypeEnum
    };
}


